services:
  gello-ros2: 
    build: .
    privileged: true
    restart: no
    network_mode: host
    init: true # Ensure signal forwarding to child processes
    stop_signal: SIGINT # ros2 launch needs SIGINT to shutdown gracefully
    volumes:
      - ../../:/workspace
      - /dev/serial/by-id:/dev/serial/by-id
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSH: "1"
      XAUTHORITY: /tmp/.docker.xauth
      